### ISSUE TITLE
Tagging with propagation (WUI)

### ISSUE THREAD

**Issue by alainbodiguel** [gisaia/ARLAS-wui#133]
Tagging with propagation requires that the user is presented with the following fields in ARLAS WUI:
- Label (optional or auto-generated?)
- Tag field
- Tag value
- checkbox for optional propagation request with fields:
  - Keyword field to propagate on
  - optional bookmark

The Tag/Untag buttons should send a request to the ARLAS Tagger service, with the following endpoints:
- `http://<arlas-tagger-host>:<arlas-tagger-port>/arlas/write/{collection}/_tag`
- `http://<arlas-tagger-host>:<arlas-tagger-port>/arlas/write/{collection}/_untag`

The JSON body should contain follow this model: 
```json
{
  "search": {
    "filter": {
        <arlas filter specification>
    }
  },
  "tag": {
    "path": "labels.trainingset",
    "value": "mytag"
  },
  "propagation": {
    "field": "obu.obu_id",
    "filter": {
        <arlas filter specification>
    }
  },
  "label": "Barcelona"
}
```

The request will respond with:  
```json
{
  "failed": 0,
  "updated": 0,
  "progress": 0,
  "id": "1d5b316a-cd97-49e9-8d63-ca975057a574",
  "propagated": 0,
  "startTime": 1560340555914,
  "endTime": 1560340555914,
  "processingTimeMs": 0 // ms
}
```

The status of the propagation can be requested with the `id`specified in the tag response to the following endpoint:  
- `http://<arlas-tagger-host>:<arlas-tagger-port>/arlas/status/{collection}/_tagging?id={id}&pretty=false`

which will reply with:  
```json
{
  "failed": 0,
  "updated": 26317, // nb of hits tagged
  "progress": 34, // progress percentage
  "id": "d2bfd346-909e-4349-9ddd-8b766b680a75",
  "action": "ADD",
  "propagated": 571, // nb of propagated objects
  "startTime": 1560341746869,
  "endTime": 1560341755854,
  "processingTimeMs": 8985 // process time in ms
}
```

**Comment by sebbousquet** [comment]
Close by gisaia/ARLAS-wui-toolkit#167
