### ISSUE TITLE
Use the mapComponent outputs directly in the html

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#134]
we subscribe to 
- [x] `onStyleChanged`, 
- [x] `onMapLoaded`
- [x]  `switchLayer` 
in the ts instead of using them as outputs in the HTML

**Comment by sebbousquet** [comment]
`onStyleChanged` and `switchLayer` have been removed.
The issue is still true for `onMapLoaded`
