### ISSUE TITLE
Map: Two aggregation levels presented at once

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#143]
When I open a link on ARLAS WUI (such as the one provided below) that contains a filter and an extend,
I expect to see the map presenting the right aggregation level given the zoom level
But instead, I get at first a map with an aggregation level that is less precise that what is expected, then some seconds afterwards a finer aggregation is presented on the map combined with the preceeding one, instead of replacing it. It is visible in "Rectangle" mode more than on "Heat" map.

- It is not always true
- On latest chrome, safari and firefox. 

http://demo.arlas.io/arlaswui-ais/?filter=%7B%22sog%22:%7B%22filter%22:%7B%22f%22:%5B%5B%7B%22field%22:%22course.sog%22,%22op%22:%22range%22,%22value%22:%22%5B8.317204301075268%3C180%5D%22%7D%5D%5D%7D,%22enabled%22:true%7D%7D&extend=9.558995127878546,55.72255831392323,11.81921970383749,56.359139313251546&map_styles=features:speed;cluster:fill

**Comment by mbarbet** [comment]
I confirm that there are two _geoaggregate calls with two levels of different aggregations :
- the first comes from arlas-wui-toolkit which analyzes the url and this.collaborativeService.setCollaborations
- the second comes from arlas-wui which analyzes the extent part of the url and fit the map to the bounds, the map moves and a refresh of data is done
