### ISSUE TITLE
Add percentage in "donut" widget 

### ISSUE THREAD

**Issue by WilliGautier** [gisaia/ARLAS-wui#147]
_**Context**_: The donut widget in arlas allow to visualize the proportion of population in each "class". When i put the mouse on one of the parts of the donut, i can see the name of the "class" and its absolute population.

**_As the_** user of ARLAS, _**I want to**_ see the percentage (with regard to the selection) of the "class" when my mouse is on it

_**So that**_ i can know the exact value of the proportion of the "class"

_**Constraints**_: I think it should appear before the absolute population or instead (choice)

**Comment by sebbousquet** [comment]
Moved here gisaia/ARLAS-d3/issues/121
