### ISSUE TITLE
Support serving app under URL base-path

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-wui#156]
**As** a system-administrator of ARLAS-wui

**I want to** serve ARLAS-wui under a configurable URL base-path

**So that** I can expose ARLAS-wui on Google Kubernetes Engine

---

I am looking for something similar to [ARLAS-server](https://github.com/gisaia/ARLAS-server)'s `ARLAS_APP_PATH` environment variable.

# Context

ARLAS-wui is going to be deployed on [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine). It will be exposed publicly using:

- [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)
- [Google Kubernetes Ingress Controller](https://github.com/kubernetes/ingress-gce)
- [Google Cloud HTTP(S) Load Balancer](https://cloud.google.com/load-balancing/docs/https/)

Multiple instances of ARLAS-wui will be exposed behind a single Load Balancer. URL-path-based routing will be applied to transfer requests to the desired ARLAS-wui instance.

Example:

let's consider we have two instances running as [Kubernetes pods](https://kubernetes.io/docs/concepts/workloads/pods/pod/) on GKE:

- `arlas-wui-abcd`
- `arlas-wui-fegh`

We set up the following routing:

```
Incoming request                          Target pod

google.load.balancer/arlas/wui/abcd ----> arlas-wui-abcd
google.load.balancer/arlas/wui/fegh ----> arlas-wui-fegh
```

Unfortunately, Google Kubernetes Ingress Controller does not support URL rewriting, see [here](https://issuetracker.google.com/u/2/issues/72484862) & [here](https://github.com/kubernetes/ingress-gce/issues/109).

Thus, traffic arriving at `google.load.balancer/arlas/wui/abcd` will be transfered to arlas-wui with full path `/arlas/wui/abcd`. It will result in a `HTTP 404` reply from ARLAS-wui, because ARLAS-wui is served by nginx at the root (`/`).

# Details

Let's consider a user trying to browse a UI available exposed only behind path `/arlas/wui/abcd`.

1. browser makes request GET `/arlas/wui/abcd/`

2. ARLAS-wui returns `index.html`, since the request falls in this block of the embedded-nginx's configuration: https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/nginx/default.conf#L45-L47

3. `index.html` references javascript css files the ARLAS-wui is made of. Example:

```
<script src="runtime-es2015.edb2fcf2778e7bf1d426.js" type="module"></script><script src="runtime-es5.edb2fcf2778e7bf1d426.js" nomodule defer></script><script src="polyfills-es5.c43170722f25de43ae2b.js" nomodule defer></script><script src="polyfills-es2015.7b6b54ef60d8b0b04b92.js" type="module"></script><script src="scripts.192df84feb8bcc276060.js" defer></script><script src="main-es2015.f6fda9cbd6bca7ce0a7f.js" type="module"></script><script src="main-es5.f6fda9cbd6bca7ce0a7f.js" nomodule defer></script>
```

The client's browser will try loading them. Since `base`'s `href` is empty:

https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/src/index.html#L15

... client browser will try to fetch javascript & css files relatively to original path `/arlas/wui/abcd/`.

Example: `GET /arlas/wui/abcd/runtime-es2015.edb2fcf2778e7bf1d426.js`

It returns 404, since it falls in the following nginx block: https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/nginx/default.conf#L49-L52

... so nginx will try to return non-existent file `/usr/share/nginx/html/arlas/wui/abcd/runtime-es2015.edb2fcf2778e7bf1d426.js`, while file is actually located at the root: `/usr/share/nginx/html/runtime-es2015.edb2fcf2778e7bf1d426.js`.

![image](https://user-images.githubusercontent.com/9483289/72348342-84fa7b80-36da-11ea-8601-d555b64bb57f.png)

4. In the same fashion, client browser will also try to download the app's icon, with `GET /arlas/wui/abcd/favicon.ico`. Unlike `.js` & `.css` files, request falls under this nginx-block: https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/nginx/default.conf#L45-L47

... and since file `/usr/share/nginx/html/arlas/wui/abcd/favicon.ico` does not exist, as per the configuration block nginx will return html file `/usr/share/nginx/html/index.html` instead of the icon file.

![image](https://user-images.githubusercontent.com/9483289/72348384-9774b500-36da-11ea-98f4-6cba0c9efcb8.png)

**Comment by elouanKeryell-Even** [comment]
Let's think about a solution.

Considering the `/arlas/wui/abcd` example introduced above, one solution would be to change the nginx configuration from: https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/nginx/default.conf#L43-L52

... to:

```nginx
  root /usr/share/nginx/html;

  location ~ ^/arlas/wui/abcd/(?<subpath>.+\.(?:css|js|woff2|png))$ {
    expires     30d;
    add_header  Cache-Control public;
    try_files /$subpath =404;
  }

  location ~ ^/arlas/wui/abcd(?<subpath>.+)$ {
    try_files /$subpath /$subpath/ /index.html =404;
  }
```

Consequences:

- When receiving `GET /arlas/wui/abcd/runtime-es2015.edb2fcf2778e7bf1d426.js`, nginx would return file `/usr/share/nginx/html/runtime-es2015.edb2fcf2778e7bf1d426.js` **--> fixes the issue**
- When receiving `GET /arlas/wui/abcd/favicon.ico`, nginx would return file `/usr/share/nginx/html/favicon.ico` **--> fixes the issue**

---

Now what we would want is to be able to set the base-path (here `/arlas/wui/abcd`) at **runtime**. A solution is to template the nginx configuration file using `envsubst` in the container's [start.sh file](https://github.com/gisaia/ARLAS-wui/blob/a168b22ae92deefc3fcff21ac3c3ec133358b7a4/scripts/start.sh).

The nginx configuration template would look like this:

```nginx
  root /usr/share/nginx/html;

  location ~ ^${ARLAS_WUI_APP_PATH}/(?<subpath>.+\.(?:css|js|woff2|png))$ {
    expires     30d;
    add_header  Cache-Control public;
    try_files /$subpath =404;
  }

  location ~ ^${ARLAS_WUI_APP_PATH}(?<subpath>.+)$ {
    try_files /$subpath /$subpath/ /index.html =404;
  }
```

... and `start.sh` would inject base-path in the template somehow like this:

```bash
mv /etc/nginx/conf.d/default.conf /tmp/nginx.conf

cat /tmp/nginx.conf | envsubst '${ARLAS_WUI_APP_PATH}' > /etc/nginx/conf.d/default.conf

rm -f /tmp/nginx.conf
```

**Comment by sebbousquet** [comment]
@elouanKeryell-Even I just tested your solution and it works perfectly, I've only modify one thing in your regex rule :
```
location ~ ^${ARLAS_WUI_APP_PATH}(?<subpath>.+)$ {
  try_files /$subpath /$subpath/ /index.html =404;
}
```
to 
```
location ~ ^${ARLAS_WUI_APP_PATH}(?<subpath>.*)$ {
  try_files /$subpath /$subpath/ /index.html =404;
}
```
