### ISSUE TITLE
Issue with embarked config.json file

### ISSUE THREAD

**Issue by ThomasBertiere** [gisaia/ARLAS-wui#424]
Hi, 

I'm currently using ARLAS WUI 19.2.2 and faced an issue: 

I created a dashboard through Arlas Builder and I exported its configuration files : `config.json` and `config.map.json`.

Now, I would like to run only ARLAS WUI (without ARLAS Builder, ARLAS Persistence, etc.). I saw on your documentation that my dashboard configuration files can be mounted in ARLAS WUI through a Docker volume: https://docs.arlas.io/arlas-wui-configuration/#file_1 

According to your code, these mounted configuration files are taken into account when the env var `ARLAS_PERSISTENCE_URL` is not set: 

`scripts/start.sh`
```bash
...
## PERSISTENCE
if [ -z "${ARLAS_PERSISTENCE_URL}" ]; then
  ARLAS_PERSISTENCE_URL="''"
  export ARLAS_PERSISTENCE_URL
  echo "NO ARLAS-persistence URL is specified. ARLAS-wui will load its own config.json file"
else
  echo ${ARLAS_PERSISTENCE_URL} "is used for 'persistence.url'"
fi
...
```

However, several lines above, when the env var `ARLAS_PERSISTENCE_URL` is not set, you set it with a default value :cry: . Consequently, the mounted configuration files cannot be used:

`scripts/start.sh`
```bash
...
if [ -z "${ARLAS_PERSISTENCE_URL}" ]; then
  ARLAS_PERSISTENCE_URL="http://localhost:9997"
  export ARLAS_PERSISTENCE_URL
  echo "The default ARLAS-persistence url '${ARLAS_PERSISTENCE_URL}' is used"
else
  echo ${ARLAS_PERSISTENCE_URL} "is used for 'arlas.persistence-server.url'"
fi
...
```

As a workaround, I go into my ARLAS WUI container and remove these lines in the  `/usr/share/nginx/html/settings.yaml`:

```yaml
persistence:
 url: 'http://localhost:9997'
```

In that way, my dashboard configuration files are loaded.

Thanks for your help !

**Comment by sebbousquet** [comment]
Hello, 

Thanks for the feedback.

We have published a new version of the docker image that fixes this issue :

`gisaia/arlas-wui:19.2.3`

Hope this helps

**Comment by ThomasBertiere** [comment]
Thanks ! It works fine now :smile:
