### ISSUE TITLE
Legend values are between 0 and 1 when normalizing a metric

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#445]
This behaviour is observed in network analytics and cluster layers

**Comment by WilliGautier** [comment]
![image](https://user-images.githubusercontent.com/36915512/159956254-c10955de-18d0-473f-b6eb-5f2ebf78e430.png)

**Comment by WilliGautier** [comment]
![image](https://user-images.githubusercontent.com/36915512/159963641-0035189e-615a-4186-8836-5454e22288e5.png)

**Comment by MohamedHamouGisaia** [comment]
- Fixed in gisaia/ARLAS-web-contributors#483
