### ISSUE TITLE
Choosing a bucket size in the timeline does not seem to work

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#490]
I choose YEAR
<img width="405" alt="image" src="https://user-images.githubusercontent.com/35499583/176700128-75418263-7e80-4028-bad4-2fa856117e95.png">

I get a 45 days aggregation
<img width="1833" alt="image" src="https://user-images.githubusercontent.com/35499583/176700062-e8c6f6d7-0426-42e9-94c5-a62f85b6e9dd.png">

**Comment by MohamedHamouGisaia** [comment]
Buckets are now (v23.0.0)correctly taken into account
