### ISSUE TITLE
The arlas icon in the browser tab disappeared 

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#491]
The arlas icon in the browser tab disappeared. The ones for the hub & builder are ok.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/35499583/176702249-f2f2f109-4c7f-42e7-b9a4-c4753d048248.png">

**Comment by MohamedHamouGisaia** [comment]
- Duplicate #511
