### ISSUE TITLE
If a powerbar has been defined and the grouped type of data changes, the data is not displayed as intended

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui#534]

**Comment by QuCMGisaia** [comment]
I tried to reproduce the issue, but it seems to be of a different nature than the one originally spotted, since thre powerbars are showing and

With [this configuration](https://github.com/gisaia/ARLAS-wui/files/10021119/powerbar_argonautica.zip), when switching from a keyword mapping for 'is_outlier' to integer with the ARLAS-cloud-demo argonautica script in local, the powerbars show this behavior with a tooltip showing 0 elements and the selected field showing 0 elements but still displaying elements on the map. 

![image](https://user-images.githubusercontent.com/104018401/202168472-60436fe0-7194-4baf-9836-d246cca5c174.png)

This is due to an error in the request as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/104018401/202170422-30da2d24-60ac-4a7e-b3e6-bbef425f5b3d.png)

Should there be flexibility on either side to allow for the request/display, or is this "bug" desired behavior since it is not the designed used case ?

**Comment by MohamedHamouGisaia** [comment]
Need to re-save the configuration aftert change of data mapping
