### ISSUE TITLE
Colorisation of a column fails

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#588]
Seen in ARLAS Exploration Version 23.0.3

I configure a color scheme for a field in the builder
![image](https://user-images.githubusercontent.com/35499583/210967819-208c4151-893b-4676-98d2-1d764823d802.png)

The column shows up but without the color system:
![image](https://user-images.githubusercontent.com/35499583/210967890-894129e9-899b-4ab9-b91a-e63699c216a7.png)

**Comment by MohamedHamouGisaia** [comment]
Fixed
