### ISSUE TITLE
Integrate bookmarks + download + tagger +  tour in a menu.

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#635]
### Description of the current behavior

Currently each of this actions are accessible in a dedicated button and always apparent in the application

### Description of the desired behavior

Replace the bottom-left icons with a menu with the 3 dots icon

The menu shall be structured as following:

- Share & download
- Bookmarks
     - Add bookmark
     - Manage bookmarks
- Tag
     - Add tag
     - Replay
- Replay tour

**Comment by QuCMGisaia** [comment]
![Image](https://github.com/gisaia/ARLAS-wui/assets/104018401/efe4cce8-fef8-47e7-9695-09ff1809bd2b)
