### ISSUE TITLE
Improve property window on feature click

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#673]
---> **_SPECS in the comment below_**  <---

### Description of the current behavior

The properties window, when opened, is often partially hidden due to its proportions and to its big spanning.
![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/9fe93163-99e0-4ead-9c06-5ee05b7558eb)

### Description of the desired behavior

- reduce the spanning and increase the width
- or open the property window in the grid

**Comment by MohamedHamouGisaia** [comment]
- [ ] remove pop-up
- [ ] on click open corresponding resultlist and display the corresponding detail
