### ISSUE TITLE
Add a legend for x / y in a histogram

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#688]
### Description of the current behavior

An histogram presents a distribution that is not always easy to understand:
<img width="269" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/60320264-a736-4e5d-92ad-8e9167ac60f7">

### Description of the desired behavior

Adding a legend in the tooltip would drastically help to understand the meaning of the histogram.

**Comment by MohamedHamouGisaia** [comment]
Needs complementary info:
- units 
-
