### ISSUE TITLE
Histogram : NaN values instead of negative values

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#728]
### Description of the bug

Negative values are displayed as NaN values on `x` as well as `y` axis.

![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/6132375f-7169-4d9a-8120-c607ca7de52e)

### What was the error message shown?

```JavaScript
None
```

### Steps to reproduce

- Got to the [marine measures demo](https://demo.cloud.arlas.io/arlas/wui/?filter=%7B%7D&config_id=jYjGL41Wz0KIcunMNb3c&extend=9.951427139634035,53.79021086440039,12.92384458045359,54.66598023784812&vs=Current;Amonium).
- Open the analytic panel if not visible
- Scroll to the Salinity widget
- you see the distribution with NaN values

### If the issue was noticed in the demo workspace, please specify the collection and the field. Otherwise, please link the 2 ARLAS config files.

- collection: marine measures
- field: salinity

### Which ARLAS component(s) are concerned by the bug?

Widgets - Histogram

Impacted repository :
- [ ] gisaia/ARLAS-d3#222

### ARLAS version

23.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by QuCMGisaia** [comment]
Already fixed in 25.0.0
