### ISSUE TITLE
Donut tooltip is wrongly rounded off

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui#737]
### Description of the bug

The value displayed in the tooltip is rounded off too much. In the below example the value should be 51.72% instead of 52%.

![image](https://github.com/gisaia/ARLAS-wui/assets/104018401/7c01d1d4-2b4d-4aa7-860d-6afa32a83a98)

### Steps to reproduce

- Hover over a donut's arc and compute the percentage that should be displayed

### Which ARLAS component(s) are concerned by the bug?

Widgets - Donut

### ARLAS version

24.3.0

### What browsers are you seeing the problem on?

Chrome

**Comment by MAudelGisaia** [comment]
Tooltips are in toolkit
