### ISSUE TITLE
Display Unit instead of collection name in timeline and histogram having a count

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#755]
### Description of the current behavior

Currently, aggregations with `count`, like time line,  display the count possibly followed by the collection name in the tooltip.

In timeline:
<img width="180" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/d8b0d9eb-54fd-4a00-8228-e9d612ba3d3b">

In histogram with variable in x axis and y as count:
<img width="131" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/c306bbcd-3ad7-4c5b-a02b-081d2ade0b99">

In histogram with date in x axis:
<img width="245" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/476d5f1f-d2c6-4875-8695-6e1a80175884">

### Description of the desired behavior

For histogram having time as x and count as y: display the tooltip with the configured 'Unit' for y value
For histogram having a variable (mean/max/min of variable) in x and count in y, (Distribution of a variable): display the tooltip with the configured 'Unit' for y value

**Comment by MohamedHamouGisaia** [comment]
Will be fixed with the new tooltip configuration :
- Ref gisaia/ARLAS-wui-builder#938
