### ISSUE TITLE
Logging out is not detected in other opened tabs

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#770]
### Description of the bug

- I have 2 tabs opened where I am logged in
- I log out from one tab
- The second tab doesn't detect this logging out
- I have to refresh the page

### Steps to reproduce

Same as above

### Which ARLAS component(s) are concerned by the bug?

Other

### If you chose 'Other', please specify the part(s) of ARLAS concerned by the bug.

Log out button

### ARLAS version

25.0.0-beta.12

### What browsers are you seeing the problem on?

Chrome

**Comment by mbarbet** [comment]
After investigations, it's look like an issue on the back end side.
