### ISSUE TITLE
Crop with geo filter is not active

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#790]
### Description of the bug

When downloading a product, while having a geo filter, the "Crop around geo filter" (Découper selon le filtre géographique) is not active.
Also, in the summary, the value is True, while it should be False.
![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/6a09177a-eb08-417a-8218-c89bd56af20c)
![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/be3f5bfe-abc1-4f13-8624-1558d7bee8e7)

### What was the error message shown?

```JavaScript
The checkbox can not be selected, even so a geo filter was created.
```

### Steps to reproduce

Create a geofilter (bbox) over a product, download the product.

### Which ARLAS component(s) are concerned by the bug?

Other

### If you chose 'Other', please specify the part(s) of ARLAS concerned by the bug.

Download

### ARLAS version

A propos ARLAS WUI 25.0.0-beta.16

### What browsers are you seeing the problem on?

Chrome

**Comment by MohamedHamouGisaia** [comment]
Fixed in arlas-web-components
