### ISSUE TITLE
Basemaps: the thumbnail of the GRAYSCALE basemap is not displayed

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#793]
### Description of the bug

Basemaps: the thumbnail of the GRAYSCALE basemap is not displayed

![image](https://github.com/gisaia/ARLAS-wui/assets/35499583/e19a1de3-627f-4371-9d3f-b007c37b2cbe)

### What was the error message shown?

```JavaScript
A generic icon is displayed instead of the actual thumbnail
```

### Steps to reproduce

Open the basemap list

### Which ARLAS component(s) are concerned by the bug?

Map

### ARLAS version

25.0.0-rc.2

### What browsers are you seeing the problem on?

Chrome

**Comment by MohamedHamouGisaia** [comment]
Fixed. It was a bad configuration of basemaps. Not a bug
