### ISSUE TITLE
[ResultList] "Zoom to" action launched from an detailed entry card closes the detailed entry card

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#800]
### Description of the bug

In the result list, if we click on an entry, a detailed entry card is opened for that entry. In that card, if we click the "Zoom to" button, the map zooms to the entry, the result list gets updated and the detailed entry card is closed. This is arms the user experience, he can be frustrated to see the card his attention is focusing on disappearing.

### What was the error message shown?

```JavaScript
The detailed entry card disappears.
```

### Steps to reproduce

- Open the result list
- Click on one entry
- In the detailed entry card, click "zoom to"

### If the issue was noticed in the demo workspace, please specify the collection and the field. Otherwise, please link the 2 ARLAS config files.

This can be seen in the "ARLAS Earth Observation" dashboard of the demo.

### Which ARLAS component(s) are concerned by the bug?

Result list

### ARLAS version

23.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by MohamedHamouGisaia** [comment]
@MAudelGisaia @QuCMGisaia 
In order to fix this bug I propose : 
- [ ] store on the arlas-wui the identifier of the currently open detail card
- [ ] on map move (due to a zoom, pan) wait until the move end and then open the card programatically given the stored id
    - [ ] if the corresponding item still exists on the resultlist open it;
    - [ ] otherwise no need.

**Comment by MAudelGisaia** [comment]
wait map move do not work well as the  result list is updated after.

**Comment by MAudelGisaia** [comment]
What do you think about leaving the details of the image you've clicked on open, whether or not they're visible on the map?

**Comment by QuCMGisaia** [comment]
I feel like it adds a behavior to the list that is not in line with its current synchronisation with the map, but it does allow to keep the focus on it even when moving around, which could be interesting. @mbarbet @sebbousquet, do you have an opinion on this?

**Comment by sebbousquet** [comment]
I think it's more coherent for the preview to disappear if it's no longer present in the resultlist.
With ARLAS, we bring the idea that everything you do causes the data displayed to change, so I don't see why in this specific case we would do things differently.
