### ISSUE TITLE
Polygon filter information pop up does not disappear when search cancelled

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#809]
### Description of the bug

When the creation of a geo-filter is launched, a small window pops up to display the area information (height, width, area). If we cancel the creation of the polygon, the window does not disappear.
<img width="295" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/e81c5146-cab2-44d9-b2bb-79b9ce061dd0">

### What was the error message shown?

```JavaScript
None, the pop up does not disappear
```

### Steps to reproduce

- launch a geo filter, like a bbox
- type on ESC from your keyboard
=> the pop up does not disappear.

### Which ARLAS component(s) are concerned by the bug?

Map

### ARLAS version

25.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by mbarbet** [comment]
We dont reproduce the bug
