### ISSUE TITLE
Layers disappear when we are zoomed in

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#817]
### Description of the bug

Display a layer which max zoom is 24. If you zoom to the latest resolution the layer disappear.

### What was the error message shown?

```JavaScript
No error is shown. This is not an error.
```

### Steps to reproduce

Discribed above.

### Which ARLAS component(s) are concerned by the bug?

Map

### ARLAS version

25.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by QuCMGisaia** [comment]
Default value for maximum zoom on old dashboards was 22, which was confusing, as layers are displayed if the zoom is strictly less than the max zoom. Since then, the default max has been raised to 23, and there is no such issue of layers disappearing with the maximum level of zoom.
