### ISSUE TITLE
Missing geo sort in datatable (result list)

### ISSUE THREAD

**Issue by WilliGautier** [gisaia/ARLAS-wui#849]
### Description of the bug

According to Sylvain, a button to geo sort has disappeared

![image](https://github.com/user-attachments/assets/430583eb-ca2b-4554-890d-5650d5169c06)

NB: The `--` is not very explicit for "no sorting"

### Steps to reproduce

Open any dashboard of [cloud.arlas.io](https://cloud.arlas.io/arlas/wui/hub/)

### Which ARLAS component(s) are concerned by the bug?

Result list

### ARLAS version

25.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by mbarbet** [comment]
It's not a bug from arlas wui but a problem with the migration of the dashboard. Just save the dashboard in the builder to fix it. We will fix the migration processing

**Comment by mbarbet** [comment]
It's ok , just active the geosort in the dahboard

**Comment by mbarbet** [comment]
![Capture d’écran 2024-07-31 à 13 01 48](https://github.com/user-attachments/assets/b83e0ea5-59e1-4320-a946-d79bec6ebd3d)
