### ISSUE TITLE
Bookmarks can not be selected

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#875]
### Description of the bug

When we want to open a bookmark, we want to open the list of bookmarks and then select one to be opened.
Currently, bookmarks are not selectable
![image](https://github.com/user-attachments/assets/251daa21-b5e9-4a17-ad1a-5306de41f9b9)

It would be great to access a bookmark just by clicking on it. Also, bookmark functions are a bit hidden at the bottom left. Could be more accessible.

### What was the error message shown?

```JavaScript
None: the bookmark is not selectable. To open a bookmark, you need to click on the three dots, then click Visualise, then close the bookmarks.
```

### Steps to reproduce

- Create some bookmarks
- Open the bookmarks
- click on one bookmark (nothing happens)

### Which ARLAS component(s) are concerned by the bug?

Other

### If you chose 'Other', please specify the part(s) of ARLAS concerned by the bug.

bookmarks

### ARLAS version

ARLAS WUI 26.0.2

### What browsers are you seeing the problem on?

Chrome

**Comment by QuCMGisaia** [comment]
To visualize the bookmark, there is the menu on the right that then displays the view action. What you would like is to be able to view the bookmark directly by clicking on it anywhere but the checkbox, isn't it ?

**Comment by sylvaingaudan** [comment]
Yes, sounds more straight forward I believe.
